-- Faza 3: seed katalogu — popularne akcje (S&P 500 + extras) i ETF-y (curated top wg AUM),
-- przefiltrowane przez metadane Twelve Data (643 wierszy). Wygenerowane przez
-- scripts/generate-catalog-seed.ts (patrz tam: jak rozszerzyć). ON CONFLICT DO NOTHING.
insert into public.asset_definitions (asset_id, category, api_source, api_symbol, display_name, exchange, country) values
  ('MMM', 'stock', 'twelve_data', 'MMM', '3M Company', 'NYSE', 'United States'),
  ('AOS', 'stock', 'twelve_data', 'AOS', 'A. O. Smith Corporation', 'NYSE', 'United States'),
  ('ABT', 'stock', 'twelve_data', 'ABT', 'Abbott Laboratories', 'NYSE', 'United States'),
  ('ABBV', 'stock', 'twelve_data', 'ABBV', 'AbbVie Inc.', 'NYSE', 'United States'),
  ('ACN', 'stock', 'twelve_data', 'ACN', 'Accenture plc Class A', 'NYSE', 'United States'),
  ('ADBE', 'stock', 'twelve_data', 'ADBE', 'Adobe Inc.', 'NASDAQ', 'United States'),
  ('AMD', 'stock', 'twelve_data', 'AMD', 'Advanced Micro Devices, Inc.', 'NASDAQ', 'United States'),
  ('AES', 'stock', 'twelve_data', 'AES', 'AES Corporation', 'NYSE', 'United States'),
  ('AFL', 'stock', 'twelve_data', 'AFL', 'Aflac Inc.', 'NYSE', 'United States'),
  ('A', 'stock', 'twelve_data', 'A', 'Agilent Technologies Inc.', 'NYSE', 'United States'),
  ('APD', 'stock', 'twelve_data', 'APD', 'Air Products and Chemicals, Inc.', 'NYSE', 'United States'),
  ('ABNB', 'stock', 'twelve_data', 'ABNB', 'Airbnb, Inc.', 'NASDAQ', 'United States'),
  ('AKAM', 'stock', 'twelve_data', 'AKAM', 'Akamai Technologies Inc.', 'NASDAQ', 'United States'),
  ('ALB', 'stock', 'twelve_data', 'ALB', 'Albemarle Corporation', 'NYSE', 'United States'),
  ('ARE', 'stock', 'twelve_data', 'ARE', 'Alexandria Real Estate Equities, Inc.', 'NYSE', 'United States'),
  ('ALGN', 'stock', 'twelve_data', 'ALGN', 'Align Technology, Inc.', 'NASDAQ', 'United States'),
  ('ALLE', 'stock', 'twelve_data', 'ALLE', 'Allegion plc', 'NYSE', 'United States'),
  ('LNT', 'stock', 'twelve_data', 'LNT', 'Alliant Energy Corporation', 'NASDAQ', 'United States'),
  ('ALL', 'stock', 'twelve_data', 'ALL', 'Allstate Corporation', 'NYSE', 'United States'),
  ('GOOGL', 'stock', 'twelve_data', 'GOOGL', 'Alphabet Inc.', 'NASDAQ', 'United States'),
  ('GOOG', 'stock', 'twelve_data', 'GOOG', 'Alphabet Inc.', 'NASDAQ', 'United States'),
  ('MO', 'stock', 'twelve_data', 'MO', 'Altria Group, Inc.', 'NYSE', 'United States'),
  ('AMZN', 'stock', 'twelve_data', 'AMZN', 'Amazon.com, Inc.', 'NASDAQ', 'United States'),
  ('AMCR', 'stock', 'twelve_data', 'AMCR', 'Amcor plc', 'NYSE', 'United States'),
  ('AEE', 'stock', 'twelve_data', 'AEE', 'Ameren Corporation', 'NYSE', 'United States'),
  ('AEP', 'stock', 'twelve_data', 'AEP', 'American Electric Power Company, Inc.', 'NASDAQ', 'United States'),
  ('AXP', 'stock', 'twelve_data', 'AXP', 'American Express Company', 'NYSE', 'United States'),
  ('AIG', 'stock', 'twelve_data', 'AIG', 'American International Group Inc.', 'NYSE', 'United States'),
  ('AMT', 'stock', 'twelve_data', 'AMT', 'American Tower Corporation', 'NYSE', 'United States'),
  ('AWK', 'stock', 'twelve_data', 'AWK', 'American Water Works Company, Inc.', 'NYSE', 'United States'),
  ('AMP', 'stock', 'twelve_data', 'AMP', 'Ameriprise Financial, Inc.', 'NYSE', 'United States'),
  ('AME', 'stock', 'twelve_data', 'AME', 'Ametek Inc.', 'NYSE', 'United States'),
  ('AMGN', 'stock', 'twelve_data', 'AMGN', 'Amgen Inc.', 'NASDAQ', 'United States'),
  ('APH', 'stock', 'twelve_data', 'APH', 'Amphenol Corporation', 'NYSE', 'United States'),
  ('ADI', 'stock', 'twelve_data', 'ADI', 'Analog Devices, Inc.', 'NASDAQ', 'United States'),
  ('AON', 'stock', 'twelve_data', 'AON', 'Aon plc', 'NYSE', 'United States'),
  ('APA', 'stock', 'twelve_data', 'APA', 'APA Corporation', 'NASDAQ', 'United States'),
  ('APO', 'stock', 'twelve_data', 'APO', 'Apollo Global Management, Inc.', 'NYSE', 'United States'),
  ('AAPL', 'stock', 'twelve_data', 'AAPL', 'Apple Inc.', 'NASDAQ', 'United States'),
  ('AMAT', 'stock', 'twelve_data', 'AMAT', 'Applied Materials, Inc.', 'NASDAQ', 'United States'),
  ('APP', 'stock', 'twelve_data', 'APP', 'AppLovin Corporation Class A Common Stock', 'NASDAQ', 'United States'),
  ('APTV', 'stock', 'twelve_data', 'APTV', 'Aptiv PLC', 'NYSE', 'United States'),
  ('ACGL', 'stock', 'twelve_data', 'ACGL', 'Arch Capital Group Ltd', 'NASDAQ', 'United States'),
  ('ADM', 'stock', 'twelve_data', 'ADM', 'Archer-Daniels-Midland Co', 'NYSE', 'United States'),
  ('ARES', 'stock', 'twelve_data', 'ARES', 'Ares Management Corporation', 'NYSE', 'United States'),
  ('ANET', 'stock', 'twelve_data', 'ANET', 'Arista Networks, Inc.', 'NYSE', 'United States'),
  ('AJG', 'stock', 'twelve_data', 'AJG', 'Arthur J. Gallagher & Co.', 'NYSE', 'United States'),
  ('AIZ', 'stock', 'twelve_data', 'AIZ', 'Assurant Inc.', 'NYSE', 'United States'),
  ('T', 'stock', 'twelve_data', 'T', 'AT&T Inc.', 'NYSE', 'United States'),
  ('ATO', 'stock', 'twelve_data', 'ATO', 'Atmos Energy Corporation', 'NYSE', 'United States'),
  ('ADSK', 'stock', 'twelve_data', 'ADSK', 'Autodesk, Inc.', 'NASDAQ', 'United States'),
  ('ADP', 'stock', 'twelve_data', 'ADP', 'Automatic Data Processing Inc.', 'NASDAQ', 'United States'),
  ('AZO', 'stock', 'twelve_data', 'AZO', 'AutoZone Inc.', 'NYSE', 'United States'),
  ('AVB', 'stock', 'twelve_data', 'AVB', 'AvalonBay Communities, Inc.', 'NYSE', 'United States'),
  ('AVY', 'stock', 'twelve_data', 'AVY', 'Avery Dennison Corporation', 'NYSE', 'United States'),
  ('AXON', 'stock', 'twelve_data', 'AXON', 'Axon Enterprise, Inc.', 'NASDAQ', 'United States'),
  ('BKR', 'stock', 'twelve_data', 'BKR', 'Baker Hughes Company', 'NASDAQ', 'United States'),
  ('BALL', 'stock', 'twelve_data', 'BALL', 'Ball Corp.', 'NYSE', 'United States'),
  ('BAC', 'stock', 'twelve_data', 'BAC', 'Bank of America Corporation', 'NYSE', 'United States'),
  ('BAX', 'stock', 'twelve_data', 'BAX', 'Baxter International Inc.', 'NYSE', 'United States'),
  ('BDX', 'stock', 'twelve_data', 'BDX', 'Becton, Dickinson and Company', 'NYSE', 'United States'),
  ('BRK-B', 'stock', 'twelve_data', 'BRK-B', 'Berkshire Hathaway Inc. Class B', 'NYSE', 'United States'),
  ('BBY', 'stock', 'twelve_data', 'BBY', 'Best Buy Co., Inc.', 'NYSE', 'United States'),
  ('TECH', 'stock', 'twelve_data', 'TECH', 'Bio-Techne Corporation', 'NASDAQ', 'United States'),
  ('BIIB', 'stock', 'twelve_data', 'BIIB', 'Biogen Inc.', 'NASDAQ', 'United States'),
  ('BLK', 'stock', 'twelve_data', 'BLK', 'BlackRock, Inc.', 'NYSE', 'United States'),
  ('BX', 'stock', 'twelve_data', 'BX', 'Blackstone Inc.', 'NYSE', 'United States'),
  ('XYZ', 'stock', 'twelve_data', 'XYZ', 'Block, Inc.', 'NYSE', 'United States'),
  ('BNY', 'stock', 'twelve_data', 'BNY', 'BlackRock New York Municipal Income Trust', 'NYSE', 'United States'),
  ('BA', 'stock', 'twelve_data', 'BA', 'Boeing Company', 'NYSE', 'United States'),
  ('BKNG', 'stock', 'twelve_data', 'BKNG', 'Booking Holdings Inc.', 'NASDAQ', 'United States'),
  ('BSX', 'stock', 'twelve_data', 'BSX', 'Boston Scientific Corporation', 'NYSE', 'United States'),
  ('BMY', 'stock', 'twelve_data', 'BMY', 'Bristol-Myers Squibb Company', 'NYSE', 'United States'),
  ('AVGO', 'stock', 'twelve_data', 'AVGO', 'Broadcom Inc.', 'NASDAQ', 'United States'),
  ('BR', 'stock', 'twelve_data', 'BR', 'Broadridge Financial Solutions, Inc.', 'NYSE', 'United States'),
  ('BRO', 'stock', 'twelve_data', 'BRO', 'Brown & Brown Inc.', 'NYSE', 'United States'),
  ('BF-B', 'stock', 'twelve_data', 'BF-B', 'Brown-Forman Corporation', 'NYSE', 'United States'),
  ('BLDR', 'stock', 'twelve_data', 'BLDR', 'Builders FirstSource Inc.', 'NYSE', 'United States'),
  ('BG', 'stock', 'twelve_data', 'BG', 'Bunge Global S.A.', 'NYSE', 'United States'),
  ('BXP', 'stock', 'twelve_data', 'BXP', 'Boston Properties, Inc.', 'NYSE', 'United States'),
  ('CHRW', 'stock', 'twelve_data', 'CHRW', 'C.H. Robinson Worldwide, Inc.', 'NASDAQ', 'United States'),
  ('CDNS', 'stock', 'twelve_data', 'CDNS', 'Cadence Design Systems, Inc.', 'NASDAQ', 'United States'),
  ('CPT', 'stock', 'twelve_data', 'CPT', 'Camden Property Trust', 'NYSE', 'United States'),
  ('COF', 'stock', 'twelve_data', 'COF', 'Capital One Financial Corporation', 'NYSE', 'United States'),
  ('CAH', 'stock', 'twelve_data', 'CAH', 'Cardinal Health Inc.', 'NYSE', 'United States'),
  ('CCL', 'stock', 'twelve_data', 'CCL', 'Carnival Corporation Ltd.', 'NYSE', 'United States'),
  ('CARR', 'stock', 'twelve_data', 'CARR', 'Carrier Global Corporation', 'NYSE', 'United States'),
  ('CVNA', 'stock', 'twelve_data', 'CVNA', 'Carvana Co.', 'NYSE', 'United States'),
  ('CASY', 'stock', 'twelve_data', 'CASY', 'Casey''s General Stores Inc.', 'NASDAQ', 'United States'),
  ('CAT', 'stock', 'twelve_data', 'CAT', 'Caterpillar Inc.', 'NYSE', 'United States'),
  ('CBRE', 'stock', 'twelve_data', 'CBRE', 'CBRE Group Inc.', 'NYSE', 'United States'),
  ('CDW', 'stock', 'twelve_data', 'CDW', 'CDW Corporation', 'NASDAQ', 'United States'),
  ('COR', 'stock', 'twelve_data', 'COR', 'Cencora, Inc.', 'NYSE', 'United States'),
  ('CNC', 'stock', 'twelve_data', 'CNC', 'Centene Corporation', 'NYSE', 'United States'),
  ('CNP', 'stock', 'twelve_data', 'CNP', 'CenterPoint Energy Inc.', 'NYSE', 'United States'),
  ('CF', 'stock', 'twelve_data', 'CF', 'CF Industries Holdings, Inc.', 'NYSE', 'United States'),
  ('CRL', 'stock', 'twelve_data', 'CRL', 'Charles River Laboratories International, Inc.', 'NYSE', 'United States'),
  ('SCHW', 'stock', 'twelve_data', 'SCHW', 'Charles Schwab Corporation', 'NYSE', 'United States'),
  ('CHTR', 'stock', 'twelve_data', 'CHTR', 'Charter Communications Inc', 'NASDAQ', 'United States'),
  ('CVX', 'stock', 'twelve_data', 'CVX', 'Chevron Corporation', 'NYSE', 'United States'),
  ('CMG', 'stock', 'twelve_data', 'CMG', 'Chipotle Mexican Grill, Inc.', 'NYSE', 'United States'),
  ('CB', 'stock', 'twelve_data', 'CB', 'Chubb Limited', 'NYSE', 'United States'),
  ('CHD', 'stock', 'twelve_data', 'CHD', 'Church & Dwight Co., Inc.', 'NYSE', 'United States'),
  ('CIEN', 'stock', 'twelve_data', 'CIEN', 'Ciena Corporation', 'NYSE', 'United States'),
  ('CI', 'stock', 'twelve_data', 'CI', 'The Cigna Group', 'NYSE', 'United States'),
  ('CINF', 'stock', 'twelve_data', 'CINF', 'Cincinnati Financial Corporation', 'NASDAQ', 'United States'),
  ('CTAS', 'stock', 'twelve_data', 'CTAS', 'Cintas Corporation', 'NASDAQ', 'United States'),
  ('CSCO', 'stock', 'twelve_data', 'CSCO', 'Cisco Systems, Inc.', 'NASDAQ', 'United States'),
  ('C', 'stock', 'twelve_data', 'C', 'Citigroup Inc.', 'NYSE', 'United States'),
  ('CFG', 'stock', 'twelve_data', 'CFG', 'Citizens Financial Group, Inc.', 'NYSE', 'United States'),
  ('CLX', 'stock', 'twelve_data', 'CLX', 'The Clorox Company', 'NYSE', 'United States'),
  ('CME', 'stock', 'twelve_data', 'CME', 'CME Group Inc.', 'NASDAQ', 'United States'),
  ('CMS', 'stock', 'twelve_data', 'CMS', 'CMS Energy Corporation', 'NYSE', 'United States'),
  ('KO', 'stock', 'twelve_data', 'KO', 'The Coca-Cola Company', 'NYSE', 'United States'),
  ('CTSH', 'stock', 'twelve_data', 'CTSH', 'Cognizant Technology Solutions Corporation', 'NASDAQ', 'United States'),
  ('COHR', 'stock', 'twelve_data', 'COHR', 'Coherent Corp.', 'NYSE', 'United States'),
  ('COIN', 'stock', 'twelve_data', 'COIN', 'Coinbase Global, Inc.', 'NASDAQ', 'United States'),
  ('CL', 'stock', 'twelve_data', 'CL', 'Colgate-Palmolive Company', 'NYSE', 'United States'),
  ('CMCSA', 'stock', 'twelve_data', 'CMCSA', 'Comcast Corp', 'NASDAQ', 'United States'),
  ('FIX', 'stock', 'twelve_data', 'FIX', 'Comfort Systems USA, Inc.', 'NYSE', 'United States'),
  ('CAG', 'stock', 'twelve_data', 'CAG', 'Conagra Brands Inc.', 'NYSE', 'United States'),
  ('COP', 'stock', 'twelve_data', 'COP', 'ConocoPhillips', 'NYSE', 'United States'),
  ('ED', 'stock', 'twelve_data', 'ED', 'Consolidated Edison, Inc.', 'NYSE', 'United States'),
  ('STZ', 'stock', 'twelve_data', 'STZ', 'Constellation Brands, Inc.', 'NYSE', 'United States'),
  ('CEG', 'stock', 'twelve_data', 'CEG', 'Constellation Energy Corporation', 'NASDAQ', 'United States'),
  ('COO', 'stock', 'twelve_data', 'COO', 'The Cooper Companies, Inc.', 'NASDAQ', 'United States'),
  ('CPRT', 'stock', 'twelve_data', 'CPRT', 'Copart Inc.', 'NASDAQ', 'United States'),
  ('GLW', 'stock', 'twelve_data', 'GLW', 'Corning Incorporated', 'NYSE', 'United States'),
  ('CPAY', 'stock', 'twelve_data', 'CPAY', 'Corpay, Inc.', 'NYSE', 'United States'),
  ('CTVA', 'stock', 'twelve_data', 'CTVA', 'Corteva Inc.', 'NYSE', 'United States'),
  ('CSGP', 'stock', 'twelve_data', 'CSGP', 'CoStar Group, Inc.', 'NASDAQ', 'United States'),
  ('COST', 'stock', 'twelve_data', 'COST', 'Costco Wholesale Corporation', 'NASDAQ', 'United States'),
  ('CRH', 'stock', 'twelve_data', 'CRH', 'CRH plc', 'NYSE', 'United States'),
  ('CRWD', 'stock', 'twelve_data', 'CRWD', 'CrowdStrike Holdings, Inc.', 'NASDAQ', 'United States'),
  ('CCI', 'stock', 'twelve_data', 'CCI', 'Crown Castle Inc.', 'NYSE', 'United States'),
  ('CSX', 'stock', 'twelve_data', 'CSX', 'CSX Corporation', 'NASDAQ', 'United States'),
  ('CMI', 'stock', 'twelve_data', 'CMI', 'Cummins Inc.', 'NYSE', 'United States'),
  ('CVS', 'stock', 'twelve_data', 'CVS', 'CVS Health Corporation', 'NYSE', 'United States'),
  ('DHR', 'stock', 'twelve_data', 'DHR', 'Danaher Corporation', 'NYSE', 'United States'),
  ('DRI', 'stock', 'twelve_data', 'DRI', 'Darden Restaurants, Inc.', 'NYSE', 'United States'),
  ('DDOG', 'stock', 'twelve_data', 'DDOG', 'Datadog, Inc. Class A Common Stock', 'NASDAQ', 'United States'),
  ('DVA', 'stock', 'twelve_data', 'DVA', 'DaVita Inc.', 'NYSE', 'United States'),
  ('DECK', 'stock', 'twelve_data', 'DECK', 'Deckers Outdoor Corporation', 'NYSE', 'United States'),
  ('DE', 'stock', 'twelve_data', 'DE', 'Deere & Company', 'NYSE', 'United States'),
  ('DELL', 'stock', 'twelve_data', 'DELL', 'Dell Technologies Inc.', 'NYSE', 'United States'),
  ('DAL', 'stock', 'twelve_data', 'DAL', 'Delta Air Lines, Inc.', 'NYSE', 'United States'),
  ('DVN', 'stock', 'twelve_data', 'DVN', 'Devon Energy Corporation', 'NYSE', 'United States'),
  ('DXCM', 'stock', 'twelve_data', 'DXCM', 'DexCom, Inc.', 'NASDAQ', 'United States'),
  ('FANG', 'stock', 'twelve_data', 'FANG', 'Diamondback Energy Inc', 'NASDAQ', 'United States'),
  ('DLR', 'stock', 'twelve_data', 'DLR', 'Digital Realty Trust, Inc.', 'NYSE', 'United States'),
  ('DG', 'stock', 'twelve_data', 'DG', 'Dollar General Corporation', 'NYSE', 'United States'),
  ('DLTR', 'stock', 'twelve_data', 'DLTR', 'Dollar Tree, Inc.', 'NASDAQ', 'United States'),
  ('D', 'stock', 'twelve_data', 'D', 'Dominion Energy, Inc.', 'NYSE', 'United States'),
  ('DPZ', 'stock', 'twelve_data', 'DPZ', 'Domino''s Pizza Inc.', 'NASDAQ', 'United States'),
  ('DASH', 'stock', 'twelve_data', 'DASH', 'DoorDash, Inc.', 'NASDAQ', 'United States'),
  ('DOV', 'stock', 'twelve_data', 'DOV', 'Dover Corporation', 'NYSE', 'United States'),
  ('DOW', 'stock', 'twelve_data', 'DOW', 'Dow Inc.', 'NYSE', 'United States'),
  ('DHI', 'stock', 'twelve_data', 'DHI', 'D.R. Horton, Inc.', 'NYSE', 'United States'),
  ('DTE', 'stock', 'twelve_data', 'DTE', 'DTE Energy Company', 'NYSE', 'United States'),
  ('DUK', 'stock', 'twelve_data', 'DUK', 'Duke Energy Corporation', 'NYSE', 'United States'),
  ('DD', 'stock', 'twelve_data', 'DD', 'DuPont de Nemours Inc.', 'NYSE', 'United States'),
  ('ETN', 'stock', 'twelve_data', 'ETN', 'Eaton Corporation plc', 'NYSE', 'United States'),
  ('EBAY', 'stock', 'twelve_data', 'EBAY', 'eBay Inc.', 'NASDAQ', 'United States'),
  ('ECHO', 'stock', 'twelve_data', 'ECHO', 'Echo Global Logistics Inc', 'NASDAQ', 'United States'),
  ('ECL', 'stock', 'twelve_data', 'ECL', 'Ecolab Inc.', 'NYSE', 'United States'),
  ('EIX', 'stock', 'twelve_data', 'EIX', 'Edison International', 'NYSE', 'United States'),
  ('EW', 'stock', 'twelve_data', 'EW', 'Edwards Lifesciences Corporation', 'NYSE', 'United States'),
  ('EA', 'stock', 'twelve_data', 'EA', 'Electronic Arts Inc.', 'NASDAQ', 'United States'),
  ('ELV', 'stock', 'twelve_data', 'ELV', 'Elevance Health, Inc.', 'NYSE', 'United States'),
  ('EME', 'stock', 'twelve_data', 'EME', 'EMCOR Group, Inc.', 'NYSE', 'United States'),
  ('EMR', 'stock', 'twelve_data', 'EMR', 'Emerson Electric Co.', 'NYSE', 'United States'),
  ('ETR', 'stock', 'twelve_data', 'ETR', 'Entergy Corporation', 'NYSE', 'United States'),
  ('EOG', 'stock', 'twelve_data', 'EOG', 'EOG Resources, Inc.', 'NYSE', 'United States'),
  ('EQT', 'stock', 'twelve_data', 'EQT', 'EQT Corporation', 'NYSE', 'United States'),
  ('EFX', 'stock', 'twelve_data', 'EFX', 'Equifax Inc.', 'NYSE', 'United States'),
  ('EQIX', 'stock', 'twelve_data', 'EQIX', 'Equinix, Inc.', 'NASDAQ', 'United States'),
  ('EQR', 'stock', 'twelve_data', 'EQR', 'Equity Residential', 'NYSE', 'United States'),
  ('ERIE', 'stock', 'twelve_data', 'ERIE', 'Erie Indemnity Company', 'NASDAQ', 'United States'),
  ('ESS', 'stock', 'twelve_data', 'ESS', 'Essex Property Trust, Inc.', 'NYSE', 'United States'),
  ('EL', 'stock', 'twelve_data', 'EL', 'The Estée Lauder Companies Inc. Class A', 'NYSE', 'United States'),
  ('EG', 'stock', 'twelve_data', 'EG', 'Everest Group, Ltd.', 'NYSE', 'United States'),
  ('EVRG', 'stock', 'twelve_data', 'EVRG', 'Evergy Inc.', 'NASDAQ', 'United States'),
  ('ES', 'stock', 'twelve_data', 'ES', 'Eversource Energy', 'NYSE', 'United States'),
  ('EXC', 'stock', 'twelve_data', 'EXC', 'Exelon Corporation', 'NASDAQ', 'United States'),
  ('EXE', 'stock', 'twelve_data', 'EXE', 'Expand Energy Corporation', 'NASDAQ', 'United States'),
  ('EXPE', 'stock', 'twelve_data', 'EXPE', 'Expedia Group, Inc.', 'NASDAQ', 'United States'),
  ('EXPD', 'stock', 'twelve_data', 'EXPD', 'Expeditors International of Washington, Inc.', 'NYSE', 'United States'),
  ('EXR', 'stock', 'twelve_data', 'EXR', 'Extra Space Storage Inc.', 'NYSE', 'United States'),
  ('XOM', 'stock', 'twelve_data', 'XOM', 'Exxon Mobil Corporation', 'NYSE', 'United States'),
  ('FFIV', 'stock', 'twelve_data', 'FFIV', 'F5 Inc.', 'NASDAQ', 'United States'),
  ('FDS', 'stock', 'twelve_data', 'FDS', 'FactSet Research Systems Inc.', 'NYSE', 'United States'),
  ('FICO', 'stock', 'twelve_data', 'FICO', 'Fair Isaac Corporation', 'NYSE', 'United States'),
  ('FAST', 'stock', 'twelve_data', 'FAST', 'Fastenal Co.', 'NASDAQ', 'United States'),
  ('FRT', 'stock', 'twelve_data', 'FRT', 'Federal Realty Investment Trust', 'NYSE', 'United States'),
  ('FDX', 'stock', 'twelve_data', 'FDX', 'FedEx Corporation', 'NYSE', 'United States'),
  ('FDXF', 'stock', 'twelve_data', 'FDXF', 'FedEx Freight Holding Company Inc.', 'NYSE', 'United States'),
  ('FIS', 'stock', 'twelve_data', 'FIS', 'Fidelity National Information Services, Inc.', 'NYSE', 'United States'),
  ('FITB', 'stock', 'twelve_data', 'FITB', 'Fifth Third Bancorp', 'NASDAQ', 'United States'),
  ('FSLR', 'stock', 'twelve_data', 'FSLR', 'First Solar, Inc.', 'NASDAQ', 'United States'),
  ('FE', 'stock', 'twelve_data', 'FE', 'FirstEnergy Corp.', 'NYSE', 'United States'),
  ('FISV', 'stock', 'twelve_data', 'FISV', 'Fiserv, Inc.', 'NASDAQ', 'United States'),
  ('FLEX', 'stock', 'twelve_data', 'FLEX', 'Flex Ltd.', 'NASDAQ', 'United States'),
  ('F', 'stock', 'twelve_data', 'F', 'Ford Motor Company', 'NYSE', 'United States'),
  ('FTNT', 'stock', 'twelve_data', 'FTNT', 'Fortinet Inc.', 'NASDAQ', 'United States'),
  ('FTV', 'stock', 'twelve_data', 'FTV', 'Fortive Corporation', 'NYSE', 'United States'),
  ('FOXA', 'stock', 'twelve_data', 'FOXA', 'Fox Corporation', 'NASDAQ', 'United States'),
  ('FOX', 'stock', 'twelve_data', 'FOX', 'Fox Corporation Class B Common Stock', 'NASDAQ', 'United States'),
  ('BEN', 'stock', 'twelve_data', 'BEN', 'Franklin Resources Inc.', 'NYSE', 'United States'),
  ('FCX', 'stock', 'twelve_data', 'FCX', 'Freeport-McMoRan Inc.', 'NYSE', 'United States'),
  ('GRMN', 'stock', 'twelve_data', 'GRMN', 'Garmin Ltd.', 'NYSE', 'United States'),
  ('IT', 'stock', 'twelve_data', 'IT', 'Gartner Inc.', 'NYSE', 'United States'),
  ('GE', 'stock', 'twelve_data', 'GE', 'General Electric Company', 'NYSE', 'United States'),
  ('GEHC', 'stock', 'twelve_data', 'GEHC', 'GE HealthCare Technologies Inc.', 'NASDAQ', 'United States'),
  ('GEV', 'stock', 'twelve_data', 'GEV', 'GE Vernova Inc.', 'NYSE', 'United States'),
  ('GEN', 'stock', 'twelve_data', 'GEN', 'Gen Digital Inc.', 'NASDAQ', 'United States'),
  ('GNRC', 'stock', 'twelve_data', 'GNRC', 'Generac Holdings Inc.', 'NYSE', 'United States'),
  ('GD', 'stock', 'twelve_data', 'GD', 'General Dynamics Corporation', 'NYSE', 'United States'),
  ('GIS', 'stock', 'twelve_data', 'GIS', 'General Mills, Inc.', 'NYSE', 'United States'),
  ('GM', 'stock', 'twelve_data', 'GM', 'General Motors Company', 'NYSE', 'United States'),
  ('GPC', 'stock', 'twelve_data', 'GPC', 'Genuine Parts Company', 'NYSE', 'United States'),
  ('GILD', 'stock', 'twelve_data', 'GILD', 'Gilead Sciences Inc.', 'NASDAQ', 'United States'),
  ('GPN', 'stock', 'twelve_data', 'GPN', 'Global Payments Inc.', 'NYSE', 'United States'),
  ('GL', 'stock', 'twelve_data', 'GL', 'Globe Life Inc.', 'NYSE', 'United States'),
  ('GDDY', 'stock', 'twelve_data', 'GDDY', 'Godaddy Inc.', 'NYSE', 'United States'),
  ('GS', 'stock', 'twelve_data', 'GS', 'The Goldman Sachs Group, Inc.', 'NYSE', 'United States'),
  ('HAL', 'stock', 'twelve_data', 'HAL', 'Halliburton Company', 'NYSE', 'United States'),
  ('HIG', 'stock', 'twelve_data', 'HIG', 'The Hartford Insurance Group, Inc.', 'NYSE', 'United States'),
  ('HAS', 'stock', 'twelve_data', 'HAS', 'Hasbro Inc.', 'NASDAQ', 'United States'),
  ('HCA', 'stock', 'twelve_data', 'HCA', 'HCA Healthcare Inc.', 'NYSE', 'United States'),
  ('DOC', 'stock', 'twelve_data', 'DOC', 'Healthpeak Properties, Inc.', 'NYSE', 'United States'),
  ('HSIC', 'stock', 'twelve_data', 'HSIC', 'Henry Schein, Inc.', 'NASDAQ', 'United States'),
  ('HSY', 'stock', 'twelve_data', 'HSY', 'The Hershey Company', 'NYSE', 'United States'),
  ('HPE', 'stock', 'twelve_data', 'HPE', 'Hewlett Packard Enterprise Company', 'NYSE', 'United States'),
  ('HLT', 'stock', 'twelve_data', 'HLT', 'Hilton Worldwide Holdings Inc.', 'NYSE', 'United States'),
  ('HD', 'stock', 'twelve_data', 'HD', 'The Home Depot, Inc.', 'NYSE', 'United States'),
  ('HON', 'stock', 'twelve_data', 'HON', 'Honeywell International Inc.', 'NASDAQ', 'United States'),
  ('HRL', 'stock', 'twelve_data', 'HRL', 'Hormel Foods Corporation', 'NYSE', 'United States'),
  ('HST', 'stock', 'twelve_data', 'HST', 'Host Hotels & Resorts Inc.', 'NASDAQ', 'United States'),
  ('HWM', 'stock', 'twelve_data', 'HWM', 'Howmet Aerospace Inc.', 'NYSE', 'United States'),
  ('HPQ', 'stock', 'twelve_data', 'HPQ', 'HP Inc.', 'NYSE', 'United States'),
  ('HUBB', 'stock', 'twelve_data', 'HUBB', 'Hubbell Inc.', 'NYSE', 'United States'),
  ('HUM', 'stock', 'twelve_data', 'HUM', 'Humana Inc.', 'NYSE', 'United States'),
  ('HBAN', 'stock', 'twelve_data', 'HBAN', 'Huntington Bancshares Incorporated', 'NASDAQ', 'United States'),
  ('HII', 'stock', 'twelve_data', 'HII', 'Huntington Ingalls Industries Inc.', 'NYSE', 'United States'),
  ('IBM', 'stock', 'twelve_data', 'IBM', 'International Business Machines Corporation', 'NYSE', 'United States'),
  ('IEX', 'stock', 'twelve_data', 'IEX', 'IDEX Corporation', 'NYSE', 'United States'),
  ('IDXX', 'stock', 'twelve_data', 'IDXX', 'IDEXX Laboratories, Inc.', 'NASDAQ', 'United States'),
  ('ITW', 'stock', 'twelve_data', 'ITW', 'Illinois Tool Works Inc.', 'NYSE', 'United States'),
  ('INCY', 'stock', 'twelve_data', 'INCY', 'Incyte Corporation', 'NASDAQ', 'United States'),
  ('IR', 'stock', 'twelve_data', 'IR', 'Ingersoll Rand Inc.', 'NYSE', 'United States'),
  ('PODD', 'stock', 'twelve_data', 'PODD', 'Insulet Corporation', 'NASDAQ', 'United States'),
  ('INTC', 'stock', 'twelve_data', 'INTC', 'Intel Corporation', 'NASDAQ', 'United States'),
  ('IBKR', 'stock', 'twelve_data', 'IBKR', 'Interactive Brokers Group Inc.', 'NASDAQ', 'United States'),
  ('ICE', 'stock', 'twelve_data', 'ICE', 'Intercontinental Exchange, Inc.', 'NYSE', 'United States'),
  ('IFF', 'stock', 'twelve_data', 'IFF', 'International Flavors & Fragrances Inc.', 'NYSE', 'United States'),
  ('IP', 'stock', 'twelve_data', 'IP', 'International Paper Company', 'NYSE', 'United States'),
  ('INTU', 'stock', 'twelve_data', 'INTU', 'Intuit Inc.', 'NASDAQ', 'United States'),
  ('ISRG', 'stock', 'twelve_data', 'ISRG', 'Intuitive Surgical, Inc.', 'NASDAQ', 'United States'),
  ('IVZ', 'stock', 'twelve_data', 'IVZ', 'Invesco Ltd.', 'NYSE', 'United States'),
  ('INVH', 'stock', 'twelve_data', 'INVH', 'Invitation Homes Inc.', 'NYSE', 'United States'),
  ('IQV', 'stock', 'twelve_data', 'IQV', 'IQVIA Holdings Inc.', 'NYSE', 'United States'),
  ('IRM', 'stock', 'twelve_data', 'IRM', 'Iron Mountain Inc.', 'NYSE', 'United States'),
  ('JBHT', 'stock', 'twelve_data', 'JBHT', 'J.B. Hunt Transport Services, Inc.', 'NASDAQ', 'United States'),
  ('JBL', 'stock', 'twelve_data', 'JBL', 'Jabil Inc.', 'NYSE', 'United States'),
  ('JKHY', 'stock', 'twelve_data', 'JKHY', 'Jack Henry & Associates, Inc.', 'NASDAQ', 'United States'),
  ('J', 'stock', 'twelve_data', 'J', 'Jacobs Solutions Inc.', 'NYSE', 'United States'),
  ('JNJ', 'stock', 'twelve_data', 'JNJ', 'Johnson & Johnson', 'NYSE', 'United States'),
  ('JCI', 'stock', 'twelve_data', 'JCI', 'Johnson Controls International plc', 'NYSE', 'United States'),
  ('JPM', 'stock', 'twelve_data', 'JPM', 'JPMorgan Chase & Co.', 'NYSE', 'United States'),
  ('KVUE', 'stock', 'twelve_data', 'KVUE', 'Kenvue Inc.', 'NYSE', 'United States'),
  ('KDP', 'stock', 'twelve_data', 'KDP', 'Keurig Dr Pepper Inc.', 'NASDAQ', 'United States'),
  ('KEY', 'stock', 'twelve_data', 'KEY', 'KeyCorp', 'NYSE', 'United States'),
  ('KEYS', 'stock', 'twelve_data', 'KEYS', 'Keysight Technologies, Inc.', 'NYSE', 'United States'),
  ('KMB', 'stock', 'twelve_data', 'KMB', 'Kimberly-Clark Corporation', 'NASDAQ', 'United States'),
  ('KIM', 'stock', 'twelve_data', 'KIM', 'Kimco Realty Corporation', 'NYSE', 'United States'),
  ('KMI', 'stock', 'twelve_data', 'KMI', 'Kinder Morgan, Inc.', 'NYSE', 'United States'),
  ('KKR', 'stock', 'twelve_data', 'KKR', 'KKR & Co. Inc.', 'NYSE', 'United States'),
  ('KLAC', 'stock', 'twelve_data', 'KLAC', 'KLA Corporation', 'NASDAQ', 'United States'),
  ('KHC', 'stock', 'twelve_data', 'KHC', 'The Kraft Heinz Company', 'NASDAQ', 'United States'),
  ('KR', 'stock', 'twelve_data', 'KR', 'Kroger Co.', 'NYSE', 'United States'),
  ('LHX', 'stock', 'twelve_data', 'LHX', 'L3Harris Technologies, Inc.', 'NYSE', 'United States'),
  ('LH', 'stock', 'twelve_data', 'LH', 'Labcorp Holdings Inc.', 'NYSE', 'United States'),
  ('LRCX', 'stock', 'twelve_data', 'LRCX', 'Lam Research Corporation', 'NASDAQ', 'United States'),
  ('LVS', 'stock', 'twelve_data', 'LVS', 'Las Vegas Sands Corp.', 'NYSE', 'United States'),
  ('LDOS', 'stock', 'twelve_data', 'LDOS', 'Leidos Holdings Inc.', 'NYSE', 'United States'),
  ('LEN', 'stock', 'twelve_data', 'LEN', 'Lennar Corporation', 'NYSE', 'United States'),
  ('LII', 'stock', 'twelve_data', 'LII', 'Lennox International Inc.', 'NYSE', 'United States'),
  ('LLY', 'stock', 'twelve_data', 'LLY', 'Eli Lilly and Company', 'NYSE', 'United States'),
  ('LIN', 'stock', 'twelve_data', 'LIN', 'Linde plc', 'NASDAQ', 'United States'),
  ('LYV', 'stock', 'twelve_data', 'LYV', 'Live Nation Entertainment, Inc.', 'NYSE', 'United States'),
  ('LMT', 'stock', 'twelve_data', 'LMT', 'Lockheed Martin Corporation', 'NYSE', 'United States'),
  ('L', 'stock', 'twelve_data', 'L', 'Loews Corporation', 'NYSE', 'United States'),
  ('LOW', 'stock', 'twelve_data', 'LOW', 'Lowe''s Companies Inc.', 'NYSE', 'United States'),
  ('LULU', 'stock', 'twelve_data', 'LULU', 'lululemon athletica inc.', 'NASDAQ', 'United States'),
  ('LITE', 'stock', 'twelve_data', 'LITE', 'Lumentum Holdings Inc.', 'NASDAQ', 'United States'),
  ('LYB', 'stock', 'twelve_data', 'LYB', 'LyondellBasell Industries N.V.', 'NYSE', 'United States'),
  ('MTB', 'stock', 'twelve_data', 'MTB', 'M&T Bank Corporation', 'NYSE', 'United States'),
  ('MPC', 'stock', 'twelve_data', 'MPC', 'Marathon Petroleum Corporation', 'NYSE', 'United States'),
  ('MAR', 'stock', 'twelve_data', 'MAR', 'Marriott International Inc. - Class A', 'NASDAQ', 'United States'),
  ('MRSH', 'stock', 'twelve_data', 'MRSH', 'Marsh & McLennan Companies, Inc.', 'NYSE', 'United States'),
  ('MLM', 'stock', 'twelve_data', 'MLM', 'Martin Marietta Materials, Inc.', 'NYSE', 'United States'),
  ('MRVL', 'stock', 'twelve_data', 'MRVL', 'Marvell Technology, Inc.', 'NASDAQ', 'United States'),
  ('MAS', 'stock', 'twelve_data', 'MAS', 'Masco Corporation', 'NYSE', 'United States'),
  ('MA', 'stock', 'twelve_data', 'MA', 'Mastercard Incorporated', 'NYSE', 'United States'),
  ('MKC', 'stock', 'twelve_data', 'MKC', 'McCormick & Company, Incorporated', 'NYSE', 'United States'),
  ('MCD', 'stock', 'twelve_data', 'MCD', 'McDonald''s Corporation', 'NYSE', 'United States'),
  ('MCK', 'stock', 'twelve_data', 'MCK', 'McKesson Corporation', 'NYSE', 'United States'),
  ('MDT', 'stock', 'twelve_data', 'MDT', 'Medtronic plc', 'NYSE', 'United States'),
  ('MRK', 'stock', 'twelve_data', 'MRK', 'Merck & Co., Inc.', 'NYSE', 'United States'),
  ('META', 'stock', 'twelve_data', 'META', 'Meta Platforms Inc Class A', 'NASDAQ', 'United States'),
  ('MET', 'stock', 'twelve_data', 'MET', 'MetLife Inc.', 'NYSE', 'United States'),
  ('MTD', 'stock', 'twelve_data', 'MTD', 'Mettler-Toledo International Inc.', 'NYSE', 'United States'),
  ('MGM', 'stock', 'twelve_data', 'MGM', 'MGM Resorts International', 'NYSE', 'United States'),
  ('MCHP', 'stock', 'twelve_data', 'MCHP', 'Microchip Technology Incorporated', 'NASDAQ', 'United States'),
  ('MU', 'stock', 'twelve_data', 'MU', 'Micron Technology, Inc.', 'NASDAQ', 'United States'),
  ('MSFT', 'stock', 'twelve_data', 'MSFT', 'Microsoft Corp.', 'NASDAQ', 'United States'),
  ('MAA', 'stock', 'twelve_data', 'MAA', 'Mid-America Apartment Communities, Inc.', 'NYSE', 'United States'),
  ('MRNA', 'stock', 'twelve_data', 'MRNA', 'Moderna, Inc.', 'NASDAQ', 'United States'),
  ('TAP', 'stock', 'twelve_data', 'TAP', 'Molson Coors Beverage Company', 'NYSE', 'United States'),
  ('MDLZ', 'stock', 'twelve_data', 'MDLZ', 'Mondelez International, Inc.', 'NASDAQ', 'United States'),
  ('MPWR', 'stock', 'twelve_data', 'MPWR', 'Monolithic Power Systems, Inc.', 'NASDAQ', 'United States'),
  ('MNST', 'stock', 'twelve_data', 'MNST', 'Monster Beverage Corporation', 'NASDAQ', 'United States'),
  ('MCO', 'stock', 'twelve_data', 'MCO', 'Moody''s Corporation', 'NYSE', 'United States'),
  ('MS', 'stock', 'twelve_data', 'MS', 'Morgan Stanley', 'NYSE', 'United States'),
  ('MOS', 'stock', 'twelve_data', 'MOS', 'Mosaic Company', 'NYSE', 'United States'),
  ('MSI', 'stock', 'twelve_data', 'MSI', 'Motorola Solutions, Inc.', 'NYSE', 'United States'),
  ('MSCI', 'stock', 'twelve_data', 'MSCI', 'MSCI Inc.', 'NYSE', 'United States'),
  ('NDAQ', 'stock', 'twelve_data', 'NDAQ', 'Nasdaq, Inc.', 'NASDAQ', 'United States'),
  ('NTAP', 'stock', 'twelve_data', 'NTAP', 'NetApp, Inc.', 'NASDAQ', 'United States'),
  ('NFLX', 'stock', 'twelve_data', 'NFLX', 'Netflix, Inc.', 'NASDAQ', 'United States'),
  ('NEM', 'stock', 'twelve_data', 'NEM', 'Newmont Corporation', 'NYSE', 'United States'),
  ('NWSA', 'stock', 'twelve_data', 'NWSA', 'News Corporation', 'NASDAQ', 'United States'),
  ('NWS', 'stock', 'twelve_data', 'NWS', 'News Corporation Class B Common Stock', 'NASDAQ', 'United States'),
  ('NEE', 'stock', 'twelve_data', 'NEE', 'NextEra Energy, Inc.', 'NYSE', 'United States'),
  ('NKE', 'stock', 'twelve_data', 'NKE', 'Nike, Inc. - Class B', 'NYSE', 'United States'),
  ('NI', 'stock', 'twelve_data', 'NI', 'NiSource Inc.', 'NYSE', 'United States'),
  ('NDSN', 'stock', 'twelve_data', 'NDSN', 'Nordson Corporation', 'NASDAQ', 'United States'),
  ('NSC', 'stock', 'twelve_data', 'NSC', 'Norfolk Southern Corporation', 'NYSE', 'United States'),
  ('NTRS', 'stock', 'twelve_data', 'NTRS', 'Northern Trust Corporation', 'NASDAQ', 'United States'),
  ('NOC', 'stock', 'twelve_data', 'NOC', 'Northrop Grumman Corporation', 'NYSE', 'United States'),
  ('NCLH', 'stock', 'twelve_data', 'NCLH', 'Norwegian Cruise Line Holdings Ltd.', 'NYSE', 'United States'),
  ('NRG', 'stock', 'twelve_data', 'NRG', 'NRG Energy, Inc.', 'NYSE', 'United States'),
  ('NUE', 'stock', 'twelve_data', 'NUE', 'Nucor Corporation', 'NYSE', 'United States'),
  ('NVDA', 'stock', 'twelve_data', 'NVDA', 'NVIDIA Corporation', 'NASDAQ', 'United States'),
  ('NVR', 'stock', 'twelve_data', 'NVR', 'NVR, Inc.', 'NYSE', 'United States'),
  ('NXPI', 'stock', 'twelve_data', 'NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 'United States'),
  ('ORLY', 'stock', 'twelve_data', 'ORLY', 'O''Reilly Automotive Inc.', 'NASDAQ', 'United States'),
  ('OXY', 'stock', 'twelve_data', 'OXY', 'Occidental Petroleum Corporation', 'NYSE', 'United States'),
  ('ODFL', 'stock', 'twelve_data', 'ODFL', 'Old Dominion Freight Line, Inc.', 'NASDAQ', 'United States'),
  ('OMC', 'stock', 'twelve_data', 'OMC', 'Omnicom Group Inc.', 'NYSE', 'United States'),
  ('ON', 'stock', 'twelve_data', 'ON', 'ON Semiconductor Corporation', 'NASDAQ', 'United States'),
  ('OKE', 'stock', 'twelve_data', 'OKE', 'ONEOK, Inc.', 'NYSE', 'United States'),
  ('ORCL', 'stock', 'twelve_data', 'ORCL', 'Oracle Corporation', 'NYSE', 'United States'),
  ('OTIS', 'stock', 'twelve_data', 'OTIS', 'Otis Worldwide Corporation', 'NYSE', 'United States'),
  ('PCAR', 'stock', 'twelve_data', 'PCAR', 'PACCAR Inc.', 'NASDAQ', 'United States'),
  ('PKG', 'stock', 'twelve_data', 'PKG', 'Packaging Corporation of America', 'NYSE', 'United States'),
  ('PLTR', 'stock', 'twelve_data', 'PLTR', 'Palantir Technologies Inc.', 'NASDAQ', 'United States'),
  ('PANW', 'stock', 'twelve_data', 'PANW', 'Palo Alto Networks, Inc.', 'NASDAQ', 'United States'),
  ('PSKY', 'stock', 'twelve_data', 'PSKY', 'Paramount Skydance Corporation Class B Common Stock', 'NASDAQ', 'United States'),
  ('PH', 'stock', 'twelve_data', 'PH', 'Parker-Hannifin Corporation', 'NYSE', 'United States'),
  ('PAYX', 'stock', 'twelve_data', 'PAYX', 'Paychex Inc.', 'NASDAQ', 'United States'),
  ('PYPL', 'stock', 'twelve_data', 'PYPL', 'PayPal Holdings Inc', 'NASDAQ', 'United States'),
  ('PNR', 'stock', 'twelve_data', 'PNR', 'Pentair plc', 'NYSE', 'United States'),
  ('PEP', 'stock', 'twelve_data', 'PEP', 'PepsiCo, Inc.', 'NASDAQ', 'United States'),
  ('PFE', 'stock', 'twelve_data', 'PFE', 'Pfizer Inc.', 'NYSE', 'United States'),
  ('PCG', 'stock', 'twelve_data', 'PCG', 'PG&E Corporation', 'NYSE', 'United States'),
  ('PM', 'stock', 'twelve_data', 'PM', 'Philip Morris International Inc.', 'NYSE', 'United States'),
  ('PSX', 'stock', 'twelve_data', 'PSX', 'Phillips 66', 'NYSE', 'United States'),
  ('PNW', 'stock', 'twelve_data', 'PNW', 'Pinnacle West Capital Corporation', 'NYSE', 'United States'),
  ('PNC', 'stock', 'twelve_data', 'PNC', 'The PNC Financial Services Group, Inc.', 'NYSE', 'United States'),
  ('PPG', 'stock', 'twelve_data', 'PPG', 'PPG Industries Inc.', 'NYSE', 'United States'),
  ('PPL', 'stock', 'twelve_data', 'PPL', 'PPL Corporation', 'NYSE', 'United States'),
  ('PFG', 'stock', 'twelve_data', 'PFG', 'Principal Financial Group, Inc.', 'NASDAQ', 'United States'),
  ('PG', 'stock', 'twelve_data', 'PG', 'Procter & Gamble Co', 'NYSE', 'United States'),
  ('PGR', 'stock', 'twelve_data', 'PGR', 'Progressive Corporation', 'NYSE', 'United States'),
  ('PLD', 'stock', 'twelve_data', 'PLD', 'Prologis Inc.', 'NYSE', 'United States'),
  ('PRU', 'stock', 'twelve_data', 'PRU', 'Prudential Financial, Inc.', 'NYSE', 'United States'),
  ('PEG', 'stock', 'twelve_data', 'PEG', 'Public Service Enterprise Group Incorporated', 'NYSE', 'United States'),
  ('PTC', 'stock', 'twelve_data', 'PTC', 'PTC Inc.', 'NASDAQ', 'United States'),
  ('PSA', 'stock', 'twelve_data', 'PSA', 'Public Storage Common Stock', 'NYSE', 'United States'),
  ('PHM', 'stock', 'twelve_data', 'PHM', 'PulteGroup Inc.', 'NYSE', 'United States'),
  ('PWR', 'stock', 'twelve_data', 'PWR', 'Quanta Services Inc.', 'NYSE', 'United States'),
  ('QCOM', 'stock', 'twelve_data', 'QCOM', 'QUALCOMM Incorporated', 'NASDAQ', 'United States'),
  ('DGX', 'stock', 'twelve_data', 'DGX', 'Quest Diagnostics Inc.', 'NYSE', 'United States'),
  ('Q', 'stock', 'twelve_data', 'Q', 'Qnity Electronics Inc.', 'NYSE', 'United States'),
  ('RL', 'stock', 'twelve_data', 'RL', 'Ralph Lauren Corporation', 'NYSE', 'United States'),
  ('RJF', 'stock', 'twelve_data', 'RJF', 'Raymond James Financial Inc.', 'NYSE', 'United States'),
  ('RTX', 'stock', 'twelve_data', 'RTX', 'RTX Corporation', 'NYSE', 'United States'),
  ('O', 'stock', 'twelve_data', 'O', 'Realty Income Corporation', 'NYSE', 'United States'),
  ('REG', 'stock', 'twelve_data', 'REG', 'Regency Centers Corporation', 'NASDAQ', 'United States'),
  ('REGN', 'stock', 'twelve_data', 'REGN', 'Regeneron Pharmaceuticals, Inc.', 'NASDAQ', 'United States'),
  ('RF', 'stock', 'twelve_data', 'RF', 'Regions Financial Corporation', 'NYSE', 'United States'),
  ('RSG', 'stock', 'twelve_data', 'RSG', 'Republic Services, Inc.', 'NYSE', 'United States'),
  ('RMD', 'stock', 'twelve_data', 'RMD', 'ResMed Inc.', 'NYSE', 'United States'),
  ('RVTY', 'stock', 'twelve_data', 'RVTY', 'Revvity Inc.', 'NYSE', 'United States'),
  ('HOOD', 'stock', 'twelve_data', 'HOOD', 'Robinhood Markets, Inc.', 'NASDAQ', 'United States'),
  ('ROK', 'stock', 'twelve_data', 'ROK', 'Rockwell Automation, Inc.', 'NYSE', 'United States'),
  ('ROL', 'stock', 'twelve_data', 'ROL', 'Rollins, Inc.', 'NYSE', 'United States'),
  ('ROP', 'stock', 'twelve_data', 'ROP', 'Roper Technologies Inc.', 'NASDAQ', 'United States'),
  ('ROST', 'stock', 'twelve_data', 'ROST', 'Ross Stores, Inc.', 'NASDAQ', 'United States'),
  ('RCL', 'stock', 'twelve_data', 'RCL', 'Royal Caribbean Group', 'NYSE', 'United States'),
  ('SPGI', 'stock', 'twelve_data', 'SPGI', 'S&P Global Inc.', 'NYSE', 'United States'),
  ('CRM', 'stock', 'twelve_data', 'CRM', 'Salesforce Inc', 'NYSE', 'United States'),
  ('SNDK', 'stock', 'twelve_data', 'SNDK', 'SanDisk Corporation', 'NASDAQ', 'United States'),
  ('SBAC', 'stock', 'twelve_data', 'SBAC', 'SBA Communications Corporation', 'NASDAQ', 'United States'),
  ('SLB', 'stock', 'twelve_data', 'SLB', 'Schlumberger Limited', 'NYSE', 'United States'),
  ('STX', 'stock', 'twelve_data', 'STX', 'Seagate Technology Holdings plc', 'NASDAQ', 'United States'),
  ('SRE', 'stock', 'twelve_data', 'SRE', 'Sempra', 'NYSE', 'United States'),
  ('NOW', 'stock', 'twelve_data', 'NOW', 'ServiceNow, Inc.', 'NYSE', 'United States'),
  ('SHW', 'stock', 'twelve_data', 'SHW', 'The Sherwin-Williams Company', 'NYSE', 'United States'),
  ('SPG', 'stock', 'twelve_data', 'SPG', 'Simon Property Group, Inc.', 'NYSE', 'United States'),
  ('SWKS', 'stock', 'twelve_data', 'SWKS', 'Skyworks Solutions Inc.', 'NASDAQ', 'United States'),
  ('SJM', 'stock', 'twelve_data', 'SJM', 'The J.M. Smucker Company', 'NYSE', 'United States'),
  ('SW', 'stock', 'twelve_data', 'SW', 'Smurfit WestRock PLC', 'NYSE', 'United States'),
  ('SNA', 'stock', 'twelve_data', 'SNA', 'Snap-on Inc.', 'NYSE', 'United States'),
  ('SOLV', 'stock', 'twelve_data', 'SOLV', 'Solventum Corporation', 'NYSE', 'United States'),
  ('SO', 'stock', 'twelve_data', 'SO', 'The Southern Company', 'NYSE', 'United States'),
  ('LUV', 'stock', 'twelve_data', 'LUV', 'Southwest Airlines Co.', 'NYSE', 'United States'),
  ('SWK', 'stock', 'twelve_data', 'SWK', 'Stanley Black & Decker Inc.', 'NYSE', 'United States'),
  ('SBUX', 'stock', 'twelve_data', 'SBUX', 'Starbucks Corporation', 'NASDAQ', 'United States'),
  ('STT', 'stock', 'twelve_data', 'STT', 'State Street Corp', 'NYSE', 'United States'),
  ('STLD', 'stock', 'twelve_data', 'STLD', 'Steel Dynamics Inc.', 'NASDAQ', 'United States'),
  ('STE', 'stock', 'twelve_data', 'STE', 'STERIS plc', 'NYSE', 'United States'),
  ('SYK', 'stock', 'twelve_data', 'SYK', 'Stryker Corporation', 'NYSE', 'United States'),
  ('SMCI', 'stock', 'twelve_data', 'SMCI', 'Super Micro Computer Inc', 'NASDAQ', 'United States'),
  ('SYF', 'stock', 'twelve_data', 'SYF', 'Synchrony Financial', 'NYSE', 'United States'),
  ('SNPS', 'stock', 'twelve_data', 'SNPS', 'Synopsys, Inc.', 'NASDAQ', 'United States'),
  ('SYY', 'stock', 'twelve_data', 'SYY', 'Sysco Corporation', 'NYSE', 'United States'),
  ('TMUS', 'stock', 'twelve_data', 'TMUS', 'T-Mobile US, Inc.', 'NASDAQ', 'United States'),
  ('TROW', 'stock', 'twelve_data', 'TROW', 'T. Rowe Price Group, Inc.', 'NASDAQ', 'United States'),
  ('TTWO', 'stock', 'twelve_data', 'TTWO', 'Take-Two Interactive Software, Inc.', 'NASDAQ', 'United States'),
  ('TPR', 'stock', 'twelve_data', 'TPR', 'Tapestry Inc.', 'NYSE', 'United States'),
  ('TRGP', 'stock', 'twelve_data', 'TRGP', 'Targa Resources Corp.', 'NYSE', 'United States'),
  ('TGT', 'stock', 'twelve_data', 'TGT', 'Target Corporation', 'NYSE', 'United States'),
  ('TEL', 'stock', 'twelve_data', 'TEL', 'TE Connectivity plc', 'NYSE', 'United States'),
  ('TDY', 'stock', 'twelve_data', 'TDY', 'Teledyne Technologies Incorporated', 'NYSE', 'United States'),
  ('TER', 'stock', 'twelve_data', 'TER', 'Teradyne, Inc.', 'NASDAQ', 'United States'),
  ('TSLA', 'stock', 'twelve_data', 'TSLA', 'Tesla, Inc.', 'NASDAQ', 'United States'),
  ('TXN', 'stock', 'twelve_data', 'TXN', 'Texas Instruments Inc', 'NASDAQ', 'United States'),
  ('TPL', 'stock', 'twelve_data', 'TPL', 'Texas Pacific Land Corporation', 'NYSE', 'United States'),
  ('TXT', 'stock', 'twelve_data', 'TXT', 'Textron Inc.', 'NYSE', 'United States'),
  ('TMO', 'stock', 'twelve_data', 'TMO', 'Thermo Fisher Scientific Inc.', 'NYSE', 'United States'),
  ('TJX', 'stock', 'twelve_data', 'TJX', 'The TJX Companies, Inc.', 'NYSE', 'United States'),
  ('TKO', 'stock', 'twelve_data', 'TKO', 'Tko Group Holdings Inc.', 'NYSE', 'United States'),
  ('TTD', 'stock', 'twelve_data', 'TTD', 'The Trade Desk, Inc. Class A', 'NASDAQ', 'United States'),
  ('TSCO', 'stock', 'twelve_data', 'TSCO', 'Tractor Supply Company', 'NASDAQ', 'United States'),
  ('TT', 'stock', 'twelve_data', 'TT', 'Trane Technologies plc', 'NYSE', 'United States'),
  ('TDG', 'stock', 'twelve_data', 'TDG', 'TransDigm Group Inc.', 'NYSE', 'United States'),
  ('TRV', 'stock', 'twelve_data', 'TRV', 'The Travelers Companies, Inc.', 'NYSE', 'United States'),
  ('TRMB', 'stock', 'twelve_data', 'TRMB', 'Trimble Inc.', 'NASDAQ', 'United States'),
  ('TFC', 'stock', 'twelve_data', 'TFC', 'Truist Financial Corporation', 'NYSE', 'United States'),
  ('TYL', 'stock', 'twelve_data', 'TYL', 'Tyler Technologies Inc.', 'NYSE', 'United States'),
  ('TSN', 'stock', 'twelve_data', 'TSN', 'Tyson Foods Inc.', 'NYSE', 'United States'),
  ('USB', 'stock', 'twelve_data', 'USB', 'U.S. Bancorp', 'NYSE', 'United States'),
  ('UBER', 'stock', 'twelve_data', 'UBER', 'Uber Technologies, Inc.', 'NYSE', 'United States'),
  ('UDR', 'stock', 'twelve_data', 'UDR', 'UDR Inc.', 'NYSE', 'United States'),
  ('ULTA', 'stock', 'twelve_data', 'ULTA', 'Ulta Beauty Inc.', 'NASDAQ', 'United States'),
  ('UNP', 'stock', 'twelve_data', 'UNP', 'Union Pacific Corporation', 'NYSE', 'United States'),
  ('UAL', 'stock', 'twelve_data', 'UAL', 'United Airlines Holdings, Inc.', 'NASDAQ', 'United States'),
  ('UPS', 'stock', 'twelve_data', 'UPS', 'United Parcel Service, Inc.', 'NYSE', 'United States'),
  ('URI', 'stock', 'twelve_data', 'URI', 'United Rentals, Inc.', 'NYSE', 'United States'),
  ('UNH', 'stock', 'twelve_data', 'UNH', 'UnitedHealth Group Incorporated', 'NYSE', 'United States'),
  ('UHS', 'stock', 'twelve_data', 'UHS', 'Universal Health Services, Inc.', 'NYSE', 'United States'),
  ('VLO', 'stock', 'twelve_data', 'VLO', 'Valero Energy Corporation', 'NYSE', 'United States'),
  ('VEEV', 'stock', 'twelve_data', 'VEEV', 'Veeva Systems Inc.', 'NYSE', 'United States'),
  ('VTR', 'stock', 'twelve_data', 'VTR', 'Ventas Inc.', 'NYSE', 'United States'),
  ('VLTO', 'stock', 'twelve_data', 'VLTO', 'Veralto Corporation', 'NYSE', 'United States'),
  ('VRSN', 'stock', 'twelve_data', 'VRSN', 'Verisign Inc.', 'NASDAQ', 'United States'),
  ('VRSK', 'stock', 'twelve_data', 'VRSK', 'Verisk Analytics Inc.', 'NASDAQ', 'United States'),
  ('VZ', 'stock', 'twelve_data', 'VZ', 'Verizon Communications Inc.', 'NYSE', 'United States'),
  ('VRTX', 'stock', 'twelve_data', 'VRTX', 'Vertex Pharmaceuticals Incorporated', 'NASDAQ', 'United States'),
  ('VRT', 'stock', 'twelve_data', 'VRT', 'Vertiv Holdings Co', 'NYSE', 'United States'),
  ('VTRS', 'stock', 'twelve_data', 'VTRS', 'Viatris Inc.', 'NASDAQ', 'United States'),
  ('VICI', 'stock', 'twelve_data', 'VICI', 'Vici Properties Inc.', 'NYSE', 'United States'),
  ('V', 'stock', 'twelve_data', 'V', 'Visa Inc. Class A', 'NYSE', 'United States'),
  ('VST', 'stock', 'twelve_data', 'VST', 'Vistra Corp', 'NYSE', 'United States'),
  ('VMC', 'stock', 'twelve_data', 'VMC', 'Vulcan Materials Company', 'NYSE', 'United States'),
  ('WRB', 'stock', 'twelve_data', 'WRB', 'W.R. Berkley Corporation', 'NYSE', 'United States'),
  ('GWW', 'stock', 'twelve_data', 'GWW', 'W.W. Grainger, Inc.', 'NYSE', 'United States'),
  ('WAB', 'stock', 'twelve_data', 'WAB', 'Wabtec Corporation', 'NYSE', 'United States'),
  ('WMT', 'stock', 'twelve_data', 'WMT', 'Walmart Inc.', 'NASDAQ', 'United States'),
  ('DIS', 'stock', 'twelve_data', 'DIS', 'The Walt Disney Company', 'NYSE', 'United States'),
  ('WBD', 'stock', 'twelve_data', 'WBD', 'Warner Bros. Discovery, Inc.', 'NASDAQ', 'United States'),
  ('WM', 'stock', 'twelve_data', 'WM', 'Waste Management, Inc.', 'NYSE', 'United States'),
  ('WAT', 'stock', 'twelve_data', 'WAT', 'Waters Corporation', 'NYSE', 'United States'),
  ('WEC', 'stock', 'twelve_data', 'WEC', 'WEC Energy Group Inc.', 'NYSE', 'United States'),
  ('WFC', 'stock', 'twelve_data', 'WFC', 'Wells Fargo & Company', 'NYSE', 'United States'),
  ('WELL', 'stock', 'twelve_data', 'WELL', 'Welltower Inc.', 'NYSE', 'United States'),
  ('WST', 'stock', 'twelve_data', 'WST', 'West Pharmaceutical Services, Inc.', 'NYSE', 'United States'),
  ('WDC', 'stock', 'twelve_data', 'WDC', 'Western Digital Corporation', 'NASDAQ', 'United States'),
  ('WY', 'stock', 'twelve_data', 'WY', 'Weyerhaeuser Company', 'NYSE', 'United States'),
  ('WSM', 'stock', 'twelve_data', 'WSM', 'Williams-Sonoma, Inc.', 'NYSE', 'United States'),
  ('WMB', 'stock', 'twelve_data', 'WMB', 'The Williams Companies, Inc.', 'NYSE', 'United States'),
  ('WTW', 'stock', 'twelve_data', 'WTW', 'Willis Towers Watson Public Limited Company', 'NASDAQ', 'United States'),
  ('WDAY', 'stock', 'twelve_data', 'WDAY', 'Workday Inc.', 'NASDAQ', 'United States'),
  ('WYNN', 'stock', 'twelve_data', 'WYNN', 'Wynn Resorts, Limited', 'NASDAQ', 'United States'),
  ('XEL', 'stock', 'twelve_data', 'XEL', 'Xcel Energy Inc.', 'NASDAQ', 'United States'),
  ('XYL', 'stock', 'twelve_data', 'XYL', 'Xylem Inc.', 'NYSE', 'United States'),
  ('YUM', 'stock', 'twelve_data', 'YUM', 'Yum! Brands, Inc.', 'NYSE', 'United States'),
  ('ZBRA', 'stock', 'twelve_data', 'ZBRA', 'Zebra Technologies Corporation', 'NASDAQ', 'United States'),
  ('ZBH', 'stock', 'twelve_data', 'ZBH', 'Zimmer Biomet Holdings, Inc.', 'NYSE', 'United States'),
  ('ZTS', 'stock', 'twelve_data', 'ZTS', 'Zoetis Inc.', 'NYSE', 'United States'),
  ('RIVN', 'stock', 'twelve_data', 'RIVN', 'Rivian Automotive, Inc.', 'NASDAQ', 'United States'),
  ('LCID', 'stock', 'twelve_data', 'LCID', 'Lucid Group, Inc.', 'NASDAQ', 'United States'),
  ('SOFI', 'stock', 'twelve_data', 'SOFI', 'SoFi Technologies, Inc.', 'NASDAQ', 'United States'),
  ('MARA', 'stock', 'twelve_data', 'MARA', 'MARA Holdings Inc', 'NASDAQ', 'United States'),
  ('RIOT', 'stock', 'twelve_data', 'RIOT', 'Riot Platforms, Inc.', 'NASDAQ', 'United States'),
  ('RBLX', 'stock', 'twelve_data', 'RBLX', 'Roblox Corporation', 'NYSE', 'United States'),
  ('SNAP', 'stock', 'twelve_data', 'SNAP', 'Snap Inc.', 'NYSE', 'United States'),
  ('U', 'stock', 'twelve_data', 'U', 'Unity Software Inc.', 'NYSE', 'United States'),
  ('DKNG', 'stock', 'twelve_data', 'DKNG', 'DraftKings Inc.', 'NASDAQ', 'United States'),
  ('AFRM', 'stock', 'twelve_data', 'AFRM', 'Affirm Holdings, Inc.', 'NASDAQ', 'United States'),
  ('UPST', 'stock', 'twelve_data', 'UPST', 'Upstart Holdings, Inc.', 'NASDAQ', 'United States'),
  ('ARM', 'stock', 'twelve_data', 'ARM', 'Arm Holdings plc American Depositary Receipt', 'NASDAQ', 'United States'),
  ('MSTR', 'stock', 'twelve_data', 'MSTR', 'Strategy Inc.', 'NASDAQ', 'United States'),
  ('SPY', 'etf', 'twelve_data', 'SPY', 'SPDR S&P 500 ETF Trust', 'NYSE', 'United States'),
  ('IVV', 'etf', 'twelve_data', 'IVV', 'iShares Core S&P 500 ETF', 'NYSE', 'United States'),
  ('VOO', 'etf', 'twelve_data', 'VOO', 'Vanguard S&P 500 ETF', 'NYSE', 'United States'),
  ('VTI', 'etf', 'twelve_data', 'VTI', 'VANGUARD TOTAL STOCK MKT ETF', 'NYSE', 'United States'),
  ('QQQ', 'etf', 'twelve_data', 'QQQ', 'Invesco QQQ Trust, Series 1', 'NASDAQ', 'United States'),
  ('QQQM', 'etf', 'twelve_data', 'QQQM', 'Invesco NASDAQ 100 ETF', 'NASDAQ', 'United States'),
  ('ITOT', 'etf', 'twelve_data', 'ITOT', 'iShares Core S&P Total U.S. Stock Market ETF', 'NYSE', 'United States'),
  ('SCHX', 'etf', 'twelve_data', 'SCHX', 'Schwab U.S. Large-Cap ETF', 'NYSE', 'United States'),
  ('SCHB', 'etf', 'twelve_data', 'SCHB', 'Schwab U.S. Broad Market ETF', 'NYSE', 'United States'),
  ('VV', 'etf', 'twelve_data', 'VV', 'Vanguard Large-Cap Index Fund ETF Shares', 'NYSE', 'United States'),
  ('SPLG', 'etf', 'twelve_data', 'SPLG', 'SPDR Portfolio S&P 500 ETF', 'NYSE', 'United States'),
  ('RSP', 'etf', 'twelve_data', 'RSP', 'Invesco S&P 500 Equal Weight ETF', 'NYSE', 'United States'),
  ('VUG', 'etf', 'twelve_data', 'VUG', 'Vanguard Growth ETF', 'NYSE', 'United States'),
  ('VTV', 'etf', 'twelve_data', 'VTV', 'Vanguard Value ETF', 'NYSE', 'United States'),
  ('IWF', 'etf', 'twelve_data', 'IWF', 'iShares Russell 1000 Growth ETF', 'NYSE', 'United States'),
  ('IWD', 'etf', 'twelve_data', 'IWD', 'iShares Russell 1000 Value ETF', 'NYSE', 'United States'),
  ('VO', 'etf', 'twelve_data', 'VO', 'Vanguard Mid-Cap ETF', 'NYSE', 'United States'),
  ('VB', 'etf', 'twelve_data', 'VB', 'Vanguard Small-Cap ETF', 'NYSE', 'United States'),
  ('VBR', 'etf', 'twelve_data', 'VBR', 'VANGUARD SMALL-CAP VALUE ETF', 'NYSE', 'United States'),
  ('VBK', 'etf', 'twelve_data', 'VBK', 'Vanguard Small-Cap Growth ETF', 'NYSE', 'United States'),
  ('IJH', 'etf', 'twelve_data', 'IJH', 'iShares Core S&P Mid-Cap ETF', 'NYSE', 'United States'),
  ('IJR', 'etf', 'twelve_data', 'IJR', 'iShares Core S&P Small-Cap ETF', 'NYSE', 'United States'),
  ('MGK', 'etf', 'twelve_data', 'MGK', 'Vanguard Mega Cap Growth ETF', 'NYSE', 'United States'),
  ('SCHG', 'etf', 'twelve_data', 'SCHG', 'Schwab U.S. Large-Cap Growth ETF', 'NYSE', 'United States'),
  ('SCHD', 'etf', 'twelve_data', 'SCHD', 'Schwab U.S. Dividend Equity ETF', 'NYSE', 'United States'),
  ('SPYG', 'etf', 'twelve_data', 'SPYG', 'SPDR Portfolio S&P 500 Growth ETF', 'NYSE', 'United States'),
  ('SPYV', 'etf', 'twelve_data', 'SPYV', 'SPDR Portfolio S&P 500 Value ETF', 'NYSE', 'United States'),
  ('VOOG', 'etf', 'twelve_data', 'VOOG', 'Vanguard S&P 500 Growth ETF', 'NYSE', 'United States'),
  ('VOOV', 'etf', 'twelve_data', 'VOOV', 'Vanguard S&P 500 Value ETF', 'NYSE', 'United States'),
  ('DGRO', 'etf', 'twelve_data', 'DGRO', 'iShares Core Dividend Growth ETF', 'NYSE', 'United States'),
  ('VYM', 'etf', 'twelve_data', 'VYM', 'Vanguard High Dividend Yield ETF', 'NYSE', 'United States'),
  ('VIG', 'etf', 'twelve_data', 'VIG', 'Vanguard Dividend Appreciation ETF', 'NYSE', 'United States'),
  ('DVY', 'etf', 'twelve_data', 'DVY', 'iShares Select Dividend ETF', 'NASDAQ', 'United States'),
  ('SDY', 'etf', 'twelve_data', 'SDY', 'SPDR S&P Dividend ETF', 'NYSE', 'United States'),
  ('HDV', 'etf', 'twelve_data', 'HDV', 'iShares Core High Dividend ETF', 'NYSE', 'United States'),
  ('SPHD', 'etf', 'twelve_data', 'SPHD', 'Invesco S&P 500 High Dividend Low Volatility ETF', 'NYSE', 'United States'),
  ('NOBL', 'etf', 'twelve_data', 'NOBL', 'ProShares S&P 500 Dividend Aristocrats ETF', 'CBOE', 'United States'),
  ('MOAT', 'etf', 'twelve_data', 'MOAT', 'VanEck Morningstar Wide Moat Fund', 'CBOE', 'United States'),
  ('COWZ', 'etf', 'twelve_data', 'COWZ', 'Pacer US Cash Cows 100 ETF', 'CBOE', 'United States'),
  ('AVUV', 'etf', 'twelve_data', 'AVUV', 'Avantis U.S. Small Cap Value ETF', 'NYSE', 'United States'),
  ('VEA', 'etf', 'twelve_data', 'VEA', 'VANGUARD FTSE DEVELOPED MARKETS ETF', 'NYSE', 'United States'),
  ('IEFA', 'etf', 'twelve_data', 'IEFA', 'iShares Core MSCI EAFE ETF', 'CBOE', 'United States'),
  ('VWO', 'etf', 'twelve_data', 'VWO', 'Vanguard FTSE Emerging Markets ETF', 'NYSE', 'United States'),
  ('IEMG', 'etf', 'twelve_data', 'IEMG', 'iShares Core MSCI Emerging Markets ETF', 'NYSE', 'United States'),
  ('EFA', 'etf', 'twelve_data', 'EFA', 'iShares MSCI EAFE ETF', 'NYSE', 'United States'),
  ('EEM', 'etf', 'twelve_data', 'EEM', 'iShares MSCI Emerging Markets ETF', 'NYSE', 'United States'),
  ('VXUS', 'etf', 'twelve_data', 'VXUS', 'Vanguard Total International Stock Index Fund Investor Shares', 'NASDAQ', 'United States'),
  ('IXUS', 'etf', 'twelve_data', 'IXUS', 'iShares Core International Stock ETF', 'NASDAQ', 'United States'),
  ('VEU', 'etf', 'twelve_data', 'VEU', 'Vanguard FTSE All-World ex-US ETF', 'NYSE', 'United States'),
  ('VT', 'etf', 'twelve_data', 'VT', 'Vanguard Total World Stock ETF', 'NYSE', 'United States'),
  ('ACWI', 'etf', 'twelve_data', 'ACWI', 'iShares MSCI ACWI ETF', 'NASDAQ', 'United States'),
  ('SCHF', 'etf', 'twelve_data', 'SCHF', 'Schwab International Equity ETF', 'NYSE', 'United States'),
  ('VGK', 'etf', 'twelve_data', 'VGK', 'Vanguard FTSE Europe ETF', 'NYSE', 'United States'),
  ('EWJ', 'etf', 'twelve_data', 'EWJ', 'iShares MSCI Japan ETF', 'NYSE', 'United States'),
  ('FXI', 'etf', 'twelve_data', 'FXI', 'iShares China Large-Cap ETF', 'NYSE', 'United States'),
  ('EWZ', 'etf', 'twelve_data', 'EWZ', 'iShares MSCI Brazil ETF', 'NYSE', 'United States'),
  ('INDA', 'etf', 'twelve_data', 'INDA', 'ISHARES MSCI INDIA ETF', 'CBOE', 'United States'),
  ('VPL', 'etf', 'twelve_data', 'VPL', 'Vanguard FTSE Pacific ETF', 'NYSE', 'United States'),
  ('BND', 'etf', 'twelve_data', 'BND', 'Vanguard Total Bond Market Index Fund', 'NASDAQ', 'United States'),
  ('AGG', 'etf', 'twelve_data', 'AGG', 'iShares Core U.S. Aggregate Bond ETF', 'NYSE', 'United States'),
  ('BNDX', 'etf', 'twelve_data', 'BNDX', 'Vanguard Total International Bond ETF', 'NASDAQ', 'United States'),
  ('BNDW', 'etf', 'twelve_data', 'BNDW', 'Vanguard Total World Bond ETF', 'NASDAQ', 'United States'),
  ('TLT', 'etf', 'twelve_data', 'TLT', 'iShares 20+ Year Treasury Bond ETF', 'NASDAQ', 'United States'),
  ('IEF', 'etf', 'twelve_data', 'IEF', 'iShares 7-10 Year Treasury Bond ETF', 'NASDAQ', 'United States'),
  ('SHY', 'etf', 'twelve_data', 'SHY', 'iShares 1-3 Year Treasury Bond ETF', 'NASDAQ', 'United States'),
  ('GOVT', 'etf', 'twelve_data', 'GOVT', 'iShares U.S. Treasury Bond ETF', 'CBOE', 'United States'),
  ('LQD', 'etf', 'twelve_data', 'LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF', 'NYSE', 'United States'),
  ('VCIT', 'etf', 'twelve_data', 'VCIT', 'Vanguard Intermediate-Term Corporate Bond Fund', 'NASDAQ', 'United States'),
  ('VCSH', 'etf', 'twelve_data', 'VCSH', 'Vanguard Short-Term Corporate Bond ETF', 'NASDAQ', 'United States'),
  ('BSV', 'etf', 'twelve_data', 'BSV', 'Vanguard Short-Term Bond ETF', 'NYSE', 'United States'),
  ('MUB', 'etf', 'twelve_data', 'MUB', 'iShares National Muni Bond ETF', 'NYSE', 'United States'),
  ('VTEB', 'etf', 'twelve_data', 'VTEB', 'Vanguard Tax-Exempt Bond ETF', 'NYSE', 'United States'),
  ('HYG', 'etf', 'twelve_data', 'HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'NYSE', 'United States'),
  ('JNK', 'etf', 'twelve_data', 'JNK', 'SPDR Bloomberg High Yield Bond ETF', 'NYSE', 'United States'),
  ('EMB', 'etf', 'twelve_data', 'EMB', 'iShares J.P. Morgan USD Emerging Markets Bond ETF', 'NASDAQ', 'United States'),
  ('TIP', 'etf', 'twelve_data', 'TIP', 'iShares TIPS Bond ETF', 'NYSE', 'United States'),
  ('SCHP', 'etf', 'twelve_data', 'SCHP', 'Schwab U.S. TIPS ETF', 'NYSE', 'United States'),
  ('BIL', 'etf', 'twelve_data', 'BIL', 'SPDR Bloomberg 1-3 Month T-Bill ETF', 'NYSE', 'United States'),
  ('SGOV', 'etf', 'twelve_data', 'SGOV', 'iShares 0-3 Month Treasury Bond ETF', 'NYSE', 'United States'),
  ('SHV', 'etf', 'twelve_data', 'SHV', 'iShares Short Treasury Bond ETF', 'NASDAQ', 'United States'),
  ('MBB', 'etf', 'twelve_data', 'MBB', 'iShares MBS ETF', 'NASDAQ', 'United States'),
  ('VMBS', 'etf', 'twelve_data', 'VMBS', 'Vanguard Mortgage-Backed Securities Fund', 'NASDAQ', 'United States'),
  ('XLK', 'etf', 'twelve_data', 'XLK', 'State Street Technology Select Sector SPDR ETF', 'NYSE', 'United States'),
  ('XLF', 'etf', 'twelve_data', 'XLF', 'Financial Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLE', 'etf', 'twelve_data', 'XLE', 'Energy Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLV', 'etf', 'twelve_data', 'XLV', 'Health Care Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLY', 'etf', 'twelve_data', 'XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLP', 'etf', 'twelve_data', 'XLP', 'Consumer Staples Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLI', 'etf', 'twelve_data', 'XLI', 'Industrial Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLU', 'etf', 'twelve_data', 'XLU', 'Utilities Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLB', 'etf', 'twelve_data', 'XLB', 'Materials Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLRE', 'etf', 'twelve_data', 'XLRE', 'The Real Estate Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('XLC', 'etf', 'twelve_data', 'XLC', 'Communication Services Select Sector SPDR Fund', 'NYSE', 'United States'),
  ('VGT', 'etf', 'twelve_data', 'VGT', 'Vanguard Information Technology ETF', 'NYSE', 'United States'),
  ('VHT', 'etf', 'twelve_data', 'VHT', 'Vanguard Health Care ETF', 'NYSE', 'United States'),
  ('VFH', 'etf', 'twelve_data', 'VFH', 'Vanguard Financials ETF (primary ticker: VFH)', 'NYSE', 'United States'),
  ('SMH', 'etf', 'twelve_data', 'SMH', 'VanEck Semiconductor ETF', 'NASDAQ', 'United States'),
  ('SOXX', 'etf', 'twelve_data', 'SOXX', 'iShares Semiconductor ETF', 'NASDAQ', 'United States'),
  ('IBB', 'etf', 'twelve_data', 'IBB', 'iShares Biotechnology ETF', 'NASDAQ', 'United States'),
  ('XBI', 'etf', 'twelve_data', 'XBI', 'SPDR S&P Biotech ETF', 'NYSE', 'United States'),
  ('KRE', 'etf', 'twelve_data', 'KRE', 'SPDR S&P Regional Banking ETF', 'NYSE', 'United States'),
  ('XOP', 'etf', 'twelve_data', 'XOP', 'SPDR S&P Oil & Gas Exploration & Production ETF', 'NYSE', 'United States'),
  ('GLD', 'etf', 'twelve_data', 'GLD', 'SPDR Gold Shares', 'NYSE', 'United States'),
  ('IAU', 'etf', 'twelve_data', 'IAU', 'iShares Gold Trust', 'NYSE', 'United States'),
  ('SLV', 'etf', 'twelve_data', 'SLV', 'iShares Silver Trust', 'NYSE', 'United States'),
  ('GDX', 'etf', 'twelve_data', 'GDX', 'VanEck Gold Miners ETF', 'NYSE', 'United States'),
  ('USO', 'etf', 'twelve_data', 'USO', 'United States Oil Fund, LP', 'NYSE', 'United States'),
  ('ARKK', 'etf', 'twelve_data', 'ARKK', 'ARK Innovation ETF Fund', 'CBOE', 'United States'),
  ('ARKG', 'etf', 'twelve_data', 'ARKG', 'ARK Genomic Revolution ETF', 'CBOE', 'United States'),
  ('ARKW', 'etf', 'twelve_data', 'ARKW', 'ARK Next Generation Internet ETF', 'CBOE', 'United States'),
  ('BOTZ', 'etf', 'twelve_data', 'BOTZ', 'Global X Robotics & Artificial Intelligence ETF', 'NASDAQ', 'United States'),
  ('ICLN', 'etf', 'twelve_data', 'ICLN', 'iShares Global Clean Energy ETF', 'NASDAQ', 'United States'),
  ('TAN', 'etf', 'twelve_data', 'TAN', 'Invesco Solar ETF', 'NYSE', 'United States'),
  ('LIT', 'etf', 'twelve_data', 'LIT', 'GLOBAL X LITHIUM & BATTERY T', 'NYSE', 'United States'),
  ('URA', 'etf', 'twelve_data', 'URA', 'Global X Uranium ETF', 'NYSE', 'United States'),
  ('PAVE', 'etf', 'twelve_data', 'PAVE', 'Global X U.S. Infrastructure Development ETF', 'CBOE', 'United States'),
  ('JEPI', 'etf', 'twelve_data', 'JEPI', 'JPMorgan Equity Premium Income Fund', 'NYSE', 'United States'),
  ('JEPQ', 'etf', 'twelve_data', 'JEPQ', 'JPMorgan Nasdaq Equity Premium Income ETF', 'NASDAQ', 'United States'),
  ('SCHH', 'etf', 'twelve_data', 'SCHH', 'Schwab U.S. REIT ETF', 'NYSE', 'United States'),
  ('VNQ', 'etf', 'twelve_data', 'VNQ', 'Vanguard Real Estate ETF', 'NYSE', 'United States'),
  ('REET', 'etf', 'twelve_data', 'REET', 'iShares Global REIT ETF', 'NYSE', 'United States'),
  ('PFF', 'etf', 'twelve_data', 'PFF', 'iShares Preferred and Income Securities ETF', 'NASDAQ', 'United States'),
  ('DIA', 'etf', 'twelve_data', 'DIA', 'SPDR Dow Jones Industrial Average ETF Trust', 'NYSE', 'United States'),
  ('IWM', 'etf', 'twelve_data', 'IWM', 'iShares Russell 2000 ETF', 'NYSE', 'United States'),
  ('IWB', 'etf', 'twelve_data', 'IWB', 'iShares Russell 1000 ETF', 'NYSE', 'United States'),
  ('MDY', 'etf', 'twelve_data', 'MDY', 'SPDR S&P MidCap 400 ETF Trust', 'NYSE', 'United States'),
  ('QID', 'etf', 'twelve_data', 'QID', 'ProShares UltraShort QQQ', 'NYSE', 'United States'),
  ('SH', 'etf', 'twelve_data', 'SH', 'ProShares Short S&P500', 'NYSE', 'United States')
on conflict (asset_id) do nothing;
